### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by fivebaigei** [mokeyjay/Yandere-crawler#12]
“urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>”出现这种情况是因为什么，该怎么解决呢？

**Comment by fivebaigei** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "D:\Python\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\Python\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\Python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\Yandere-crawler-master\index.py", line 251, in run
    download(post)
  File "F:\Yandere-crawler-master\index.py", line 114, in download
    img = Http.get(post['file_url'], {'Host': 'files.yande.re', 'Referer': 'https://yande.re/post/show/' + post['id']})
  File "F:\Yandere-crawler-master\Http.py", line 16, in get
    req = urllib.request.urlopen(urllib.request.Request(url, headers=header))
  File "D:\Python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\Python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by Vepnore** [comment]
错误原因不好说，可能是服务器禁止过多的连接，也可能是网络链路出问题。
先前在建立连接的阶段我没加错误捕获，你可以把出问题的循环用这个替换：
```
    while retry_count:
        try:
            req = urllib.request.urlopen(urllib.request.Request(url, headers=header))
            try:
                return req.read()
            except:
                print('从{}下载文件时发生异常，重试下载，剩余尝试次数{}次'.format(url, retry_count))
        except:
            print('与服务器建立连接时发生异常，重试下载，剩余尝试次数{}次'.format(retry_count))
        retry_count -= 1
        sleep(10)
```
并且在文件首行加上`from time import sleep`。这并不能从本质上解决问题，只是让程序不退出，并且多个缓冲时间而已。
这是同步函数实现，所以总的运行时间可能会比较长。
