### ISSUE TITLE
能否请您修复一下问题

### ISSUE THREAD

**Issue by khvarenah** [mokeyjay/Yandere-crawler#9]
在最近的使用中，会出现证书问题（大概？

Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 974, in send
    self.connect()
  File "D:\Softwares\Python\Python39\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\Softwares\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Softwares\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Softwares\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "E:\Downloads\yande.re\Yandere-crawler-master\index.py", line 186, in run
    origin = Yandere.get_li(Yandere.get_json(page, tag_on, tags))
  File "E:\Downloads\yande.re\Yandere-crawler-master\Yandere.py", line 18, in get_json
    json_data = Http.get(url)
  File "E:\Downloads\yande.re\Yandere-crawler-master\Http.py", line 16, in get
    req = urllib.request.urlopen(urllib.request.Request(url, headers=header))
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Softwares\Python\Python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

不知道您是否还在使用该脚本，如果还在使用的话，希望您能修复一下
如果不再使用，请直接关闭问题

**Comment by Vepnore** [comment]
该问题不是代码问题。若要忽略此问题，请在文件`Http.py`的首行添加语句`import ssl`，并在同一文件第16行的`urlopen`函数中添加参数`context=ssl.SSLContext()`。这将能够绕过证书验证，但并不安全。
该问题源于根证书过期，建议通过手动安装中间证书或等待系统更新的方式解决证书问题，不建议绕过证书验证。相关问题的情况说明请参阅[DST Root CA X3 Expiration (September 2021)](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

**Comment by khvarenah** [comment]
> 该问题不是代码问题。若要忽略此问题，请在文件`Http.py`的首行添加语句`import ssl`，并在同一文件第16行的`urlopen`函数中添加参数`context=ssl.SSLContext()`。这将能够绕过证书验证，但并不安全。 该问题源于根证书过期，建议通过手动安装中间证书或等待系统更新的方式解决证书问题，不建议绕过证书验证。相关问题的情况说明请参阅[DST Root CA X3 Expiration (September 2021)](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

非常感谢！
